version: '3.8'

services:
  database:
    image: postgres:15.3-alpine
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "5432:5432"
  # backend:
  #     image: python:3.9-bullseye
  #     volumes:
  #       - ./backend/:/backend
  #     working_dir: /backend
  #     command: >
  #       bash -c "curl -sSL https://install.python-poetry.org | python3 -
  #       && /root/.local/bin/poetry install
  #       && /root/.local/bin/poetry run python3 -m hsc_api
