version: '3.9'

services:
  database:
    image: postgres:15.3-alpine
    container_name: hcs-db
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "5432:5432"
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: hcs-mqtt
    volumes:
     - ./messages/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
     - ./messages/mosquitto/config/passwordfile:/mosquitto/config/passwordfile
     - ./messages/mosquitto/config/aclfile:/mosquitto/config/aclfile
     - ./messages/mosquitto/data:/mosquitto/data
     - ./messages/mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
     - "1883:1883"
     - "9001:9001"
  # backend:
  #     image: python:3.9-bullseye
  #     volumes:
  #       - ./backend/:/backend
  #     working_dir: /backend
  #     command: >
  #       bash -c "curl -sSL https://install.python-poetry.org | python3 -
  #       && /root/.local/bin/poetry install
  #       && /root/.local/bin/poetry run python3 -m hsc_api
