version: "3.9"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.prod
    image: hcs-database:prod
    container_name: hcs-prod-database
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile.prod
    image: hcs-dbt:prod
    container_name: hcs-prod-dbt
    depends_on:
     - database
    env_file:
      - .env.prod
    entrypoint:
      - "sleep"
      - "+inf"
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: hcs-backend:prod
    container_name: hcs-prod-backend
    env_file:
      - .env.prod
    depends_on:
      - database
    ports:
      - "5055:5055"
  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.prod
    image: hcs-frontend:prod
    container_name: hcs-prod-frontend
    env_file:
      - .env.prod
    ports:
      - "192.168.1.17:5174:5173"
      - "10.0.0.1:5174:5173"
    depends_on:
      - backend