version: "3.9"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: hcs-database
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=5o3B1Lh6kJsH5ZEACndao3eG
      - POSTGRES_HOST=hcs-database
      - POSTGRES_DB=home
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: hcs-dbt
    volumes:
      - ./dbt/sustainability_assistant:/usr/sustainability_assistant
    depends_on:
     - database
    environment:
      - HCS_USER=admin
      - HCS_PASS=5o3B1Lh6kJsH5ZEACndao3eG
      - HCS_HOST=hcs-database
      - HCS_DBNAME=home
      - HCS_SCHEMA=dwh
    entrypoint:
      - "sleep"
      - "+inf"
    ports:
     - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hcs-backend
    volumes:
      - ./backend/hcs_api:/app/hcs_api
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=5o3B1Lh6kJsH5ZEACndao3eG
      - POSTGRES_HOST=hcs-database
      - POSTGRES_DB=home
      - POSTGRES_PORT=5432
    ports:
      - "5055:5055"
    depends_on:
      - database
  # frontend:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile
  #   container_name: hcs-frontend
  #   volumes:
  #     - ./webapp/src:/app/src
  #     - ./webapp/static:/app/static
  #   ports:
  #     - "0.0.0.0:5173:5173"
  #   depends_on:
  #     - backend