version: "3.9"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    image: hcs-database:dev
    container_name: hcs-dev-database
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile.dev
    image: hcs-dbt:dev
    container_name: hcs-dev-dbt
    volumes:
      - ./dbt/sustainability_assistant:/usr/sustainability_assistant
    depends_on:
     - database
    env_file:
      - .env.dev
    entrypoint:
      - "sleep"
      - "+inf"
    ports:
     - 8080:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: hcs-backend:dev
    container_name: hcs-dev-backend
    volumes:
      - ./backend/hcs_api:/code/hcs_api
    env_file:
      - .env.dev
    ports:
      - "5055:5055"
    depends_on:
      - database
  frontend:
    container_name: hcs-dev-frontend
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    image: hcs-frontend:dev
    volumes:
      - ./webapp/src:/app/src
      - ./webapp/static:/app/static
    env_file:
      - .env.dev
    ports:
      - "192.168.1.17:5173:5173"
      - "10.0.0.1:5173:5173"
    depends_on:
      - backend