sources:
  - name: raw
    schema: public
    tables:
      - name: users_new
        columns:
          - name: id
            description: Primary key of the users table
          - name: access_token
            description: Access token for authentication and authorization
          - name: name
            description: Profile name of the user
          - name: image
            description: File name of the user's profile, stored statically on webpage 
          - name: color
            description: Accent color used for differentiating users

      - name: activities
        columns:
          - name: id
            description: Primary key of the activities table
          - name: name
            description: Activity name
          - name: icon
            description: Activity emoji
          - name: value
            description: Value added when the activity is done
          - name: start_date
            description: Date from which the activity is valid
          - name: end_date
            description: Date to which the activity is valid

      - name: activity_records_new
        columns:
          - name: id
            description: Primary key of the activity_records table
          - name: activity_icon
            description: Activity emoji, used for joining with activities
          - name: user_id
            description: Foreign key to the users table
          - name: timestamp
            description: Timestamp when the activity was marked done


